---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: govau/cga-cf-bosh-cli
    tag: latest

inputs:
- name: src

outputs:
- name: build

caches:
- path: src/www/ui/.yarn_cache
- path: pkg/dep/sources

# We'll be a bit naughty and cache the following as well
- path: src/www/ui/node_modules

run:
  path: src/cmd/wwwd/ci/build.sh
