notifications:
  email: false
matrix:
  include:
  - language: go
    go: tip
    env:
      - DEP_VERSION="0.4.1"
    before_install:
      - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
      - chmod +x $GOPATH/bin/dep
    install:
      - dep ensure
    script: ci/test.sh
  - language: node_js
    node_js: node
    cache:
      yarn: true
      directories:
        - www/ui/node_modules
    before_install:
      - curl -o- -L https://yarnpkg.com/install.sh | bash
      - export PATH="$HOME/.yarn/bin:$PATH"
    script: www/ui/ci/test.sh
